name: Security Scan

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sundays
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci || npm install
        
      - name: Run npm audit
        run: npm audit
        continue-on-error: true
        
      # Add other security scanners here in the future
