name: Test and Lint

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci || npm install
        
      - name: Lint code
        run: npm run lint
        
  # Placeholder for future test job
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci || npm install
        
      - name: Run tests
        run: npm test
